language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
  # Instalación del compilador QT
  - sudo apt-get -y install libqt4-dev
  # Instalación de la librería CppUnit
  - sudo apt-get -y install libcppunit-dev
  # Instalación de dependencias para OpenCV

  - sudo apt-get install build-essential libgtk2.0-dev libjpeg-dev libtiff4-dev libjasper-dev libopenexr-dev cmake python-dev python-numpy python-tk libtbb-dev libeigen3-dev yasm libfaac-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev libx264-dev libqt4-dev libqt4-opengl-dev sphinx-common texlive-latex-extra libv4l-dev libdc1394-22-dev libavcodec-dev libavformat-dev libswscale-dev default-jdk ant libvtk5-qt4-dev


  # Instalación de las librerías OpenCV
  - curl -sL https://github.com/Itseez/opencv/archive/2.4.10.zip > opencv.zip
  - unzip opencv.zip
  - rm opencv.zip
  - mkdir opencv-build
  - cd opencv-build/
  - cmake -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_VTK=ON ../opencv-2.4.10/

  - make
  - sudo make install
  - sudo ldconfig
  - cd ..

script:
  - pwd
  - ls -la
  - ls -la opencv-build/
  - ls -la opencv-build/lib
  - ls -la /usr/local/bin
  - ls -la /usr/local/lib
  - ls -la /usr/local/include
  - qmake -project
  - qmake CamTool.travis.pro
  - make

