language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
  # Instalación del compilador QT
  - sudo apt-get -y install libqt4-dev
  # Instalación de la librería CppUnit
  - sudo apt-get -y install libcppunit-dev
  # Instalación de la librería OpenCV
  - sudo apt-get -y install libopencv-dev

script:
  # Ejecuciones de bash
  - pwd
  - ls -la
  # Compilar el proyecto
  - qmake -project
  - qmake CamTool.travis.pro
  - make
  # Ejecutar el proyecto
  - ./CamTool
  # Ejecuciones de bash
  #- ls -la
